= RAML2asciidoc

Convert your RAML (0.8 or 1.0) specification to asciidoc.

== Converting to PDF
In order to convert the generated asciidoc to PDF, you will need link:https://github.com/asciidoctor/asciidoctor-pdf[asciidoctor-pdf]. The generated asciidoc has a theme directory set to `themes/`, with `themes/fonts` as fonts directory.

== Usage
This utility can be executed from the command line.

[source, javascript]
.Render a file called 'spec.raml' using default template
----
node index.js
----

[source, javascript]
.Render a file called 'api.raml' using default template
----
node index.js -i api.raml
node index.js --input api.raml
----

[source, javascript]
.Render a file called 'api.raml' using custom template
----
node index.js -i api.raml -t myTemplate
node index.js --input api.raml --template myTemplate
----

== Flags
The program supports the following flags:
[source]
----
-i, --input             STRING    Relative path to file containing RAML spec
-t, --template          STRING    Name of Nunjucks template to use, stored in templates/<name>/template.adoc
-s, --style             STRING    asciidoctor-pdf theme name, stored in themes/<name>-theme.yml
-d, --debug             BOOLEAN   Be more verbose
-j, --json              BOOLEAN   Write parsed API to api.json
-e, --examples          BOOLEAN   Include examples in generated output
-n, --noExpand          BOOLEAN   Do not expand types in generated output
-h, --headerregex       STRING    JavaScript regex pattern, first capture group in matched resource URI's is converted to section heading
-a, --headerannotation  STRING    RAML Annotation used to identify section headings. Should be a string containing the preferred heading text
-c, --config            STRING    File containing json formatted config
----

== Config file
You can read the config from a file instead of having to use flags to define all options. Options given from the command line override those stored in the config file. Booleans will be false if they are not defined.

[source, json]
.Example config file
----
{
  "input": "spec.raml",
  "template": "default",
  "debug": true,
  "json": false,
  "examples": true,
  "noExpand": false,
  "headerregex": "\\/{version}\\/(\\w+)$",
}
----
