= {{generic.title}}
:doctype: book
:icons: font
:icon-set: fa
:pdf-stylesdir: themes
:pdf-fontsdir: themes/fonts
:pdf-style: isaac
:source-highlighter: rouge{% if generic.author %}
{{generic.author}}{% if generic.author_email %} <{{generic.author_email}}>{% endif %}{% endif %}{%if generic.version %}
{{generic.version}}{% endif %}

{{generic.description}}

== Overview

Base URI: {{generic.baseUri}}

== Paths
{% for e in endpoints %}                            {# foreach Endpoints #}
{% for m in e.methods %}                            {# foreach Methods #}
=== {{m.method}} {{e.parentPath}}{{ e.relativeUri }}
{% if m.description %}                              {# if Method Description #}
==== Description
{{m.description}}
{% endif %}                                         {# if Method Description#}
{% if m.protocols %}                                {# if Method Protocols #}
==== Protocols
{% for p in m.protocols %}                          {# foreach Method protocols #}
{{p}}
{% endfor %}                                        {# foreach Method Protocols #}
{% endif %}                                         {# if Method Protocols #}
{% if e.uriParameters %}                            {# if Endpoint URI Parameters #}
==== URI Parameters

[options="header"]
|===
| Name | Description | Type
{% for name, data in e.uriParameters %}             {# foreach URI Parameters #}
| {{data.name}}
| {{data.description}}
| {{data.type}}
{% endfor %}                                        {# foreach URI Parameters #}
|===
{% endif %}                                         {# if Endpoint URI Parameters #}
{% if m.queryParameters %}                          {# if Endpoint Query Parameters #}
==== Query Parameters

[Options="header"]
|===
| Name | Example | Type
{% for name, data in m.queryParameters %}           {# foreach Query Parameters #}
| {{data.name}}{% if data.required %} +
_required_{% else %} +
_optional_{% endif %}
| {{data.example}}
| {{data.type}}
{% endfor %}                                        {# foreach Query Parameters #}
|===
{% endif %}                                         {# if Endpoint Query Parameters #}


{% if m.body %}                                     {# if Method Body #}

==== Request
{% for type, data in m.body %}                      {# foreach Method Body #}
*Content-Type*: `{{type}}`
{% if data.example %}                               {# if Method Body Example #}
.Example request body
[source,json]
----
{{data.example | safe}}
----
{% endif %}                                         {# if Method Body Example #}
{% if data.formParameters %}                        {# if Method Form Parameters #}
==== Form Variables
[options="header"]
|===
| Name | Example | Type
{% for name, data in data.formParameters %}         {# foreach Method Form Parameters #}
| {{data.displayName}}{% if data.required %} +
_required_{% else %} +
_optional_{% endif %}
| {{data.example}}
| {{data.type}}
{% endfor %}                                        {# foreach Method Form Parameters #}
|===
{% endif %}                                         {# if Method Form Parameters #}
{% endfor %}                                        {# foreach Method Body #}
{% endif %}                                         {# if Method Body #}

{% if m.responses %}                                {# if Method Responses #}

==== Responses
{% for code, data in m.responses %}                 {# foreach Responses #}
===== {{code}}
{% for type, body in data.body %}                   {# foreach Response Body #}
*Content-Type*: `{{type}}`
{% if body.example %}                               {# if Response Body example #}
.Example response body
[source,json]
----
{{body.example | safe}}
----
{% endif %}                                         {# if Response Body example #}
{% endfor %}                                        {# foreach Response Body #}
{% endfor %}                                        {# foreach Responses #}
{% endif %}                                         {# if Method Responses #}

<<<

{% endfor %}                                        {# foreach Methods #}
{% endfor %}                                        {# foreach Endpoints #}
