{% if endpoint.header %}== {{endpoint.header | capitalize}}{% endif %}
{% for method in endpoint.methods %}
=== {% if method.displayName %}{{method.displayName}}
{% elif endpoint.displayName != endpoint.relativeUri %}{{endpoint.displayName}}
{% else %}{{method.method}} {{endpoint.fullPath}}{% endif %}

[source, http]
----
{{method.method | upper}}  {{endpoint.absoluteUri}}
----
{% if method.description %}
==== Description
{{method.description}}
{% endif %}

{% if method.protocols %}
==== Protocols
{% for p in method.protocols %}
{{p}}
{% endfor %}
{% endif %}

{% if endpoint.uriParameters %}
{% include 'uriParameters.adoc' %}
{% endif %}

{% if method.queryParameters %}
{% include 'queryParameters.adoc' %}
{% endif %}

{% if method.body %}
{% include 'methodBody.adoc' %}
{% endif %}

{% if method.responses %}
{% include 'methodResponse.adoc' %}
{% endif %}

<<<

{% endfor %}

{# Call this template recursively for children of the current endpoint #}
{% for endpoint in endpoint.resources %}
{% include 'endpointTemplate.adoc' %}
{% endfor %}
