#%RAML 0.8
title: LSNL Dealer App REST Api
version: v1
baseUri: http://dealerapp.logic-dev-lsn-n.isaac.local:8080/rest/v1

/dealer:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 13,
                "name": "C. Ardealer",
                "address": "Straat 1\n9999 AA Plaats",
                "phone": "06-12345679",
                "email": "c@ardealer.net",
                "externalReference": "000020",
                "dealerLicensePlates": [
                  "AA-BB-11",
                  "1-ABC-23"
                ]
              }
  post:
    description: |
      id is verplicht. Als andere velden ontbreken, dan worden ze niet overschreven.
    body:
      application/json:
        example: |
          {
            "id": 13,
            "name": "C. Ardealer",
            "address": "Straat 1\n9999 AA Plaats",
            "phone": "06-12345679",
            "email": "c@ardealer.net",
            "externalReference": "000020"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 13,
                "name": "C. Ardealer",
                "address": "Straat 1\n9999 AA Plaats",
                "phone": "06-12345679",
                "email": "c@ardealer.net",
                "externalReference": "000020",
                "active": true
              }
  /login:
    post:
      body:
        application/json:
          example: |
            {
              "username": "dealerx",
              "password": "P@ssw0rd",
              "deviceId": "6zZlCS9PLFAs/mBHEAHKXF0t"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status": "SUCCESS",
                  "sessionId": "xxxxx",
                  "rememberMeToken": "yyyyy"
                }
            application/json+failure-example:
              example: |
                {
                  "status": "FAILED"
                }
  /renewLogin:
    post:
      body:
        application/json:
          example: |
            {
              "token": "yyyy"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status": "SUCCESS",
                  "sessionId": "xxxxx",
                  "rememberMeToken": "yyyyy"
                }
            application/json+failure-example:
              example: |
                {
                  "status": "FAILED"
                }
  /logout:
    post:
      responses:
        204:
  /changePassword:
    post:
      body:
        application/json:
          example: |
            {
              "username": "dealerx",
              "password": "P@ssw0rd",
              "newPassword": "W@chtw00rd",
              "deviceId": "6zZlCS9PLFAs/mBHEAHKXF0t"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status": "SUCCESS",
                  "sessionId": "xxxxx",
                  "rememberMeToken": "yyyyy"
                }
            application/json+failure-example:
              example: |
                {
                  "status": "FAILED"
                }
  /testdrives:
    get:
      description: Geeft de testritten van de afgelopen 30 dagen.
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "id": 1,
                    "customerName": "Hans de Vries",
                    "customerPhone": "06-12345678",
                    "customerEmail": "Hans@devries.nl",
                    "started": "2015-09-17 09:13",
                    "returned": "2015-09-17 09:48",
                    "duration": 35,
                    "licensePlate": "11-22-AA",
                    "licensePlateDealer": "12-ABC-3",
                    "customerDriversLicenseUploaded": false
                  }
                ]
    post:
      body:
        multipart/form-data:
          formParameters:
            customerName:
              example: Hans de Vries
            customerPhone:
              example: 06-12345678
            customerEmail:
              example: hans@devries.nl
            customerDriversLicense:
              type: file
            licensePlate:
              example: 11-22-AA
            licensePlateDealer:
              example: 12-ABC-3
            carImage:
              type: file
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "customerName": "Hans de Vries",
                  "customerPhone": "06-12345678",
                  "customerEmail": "Hans@devries.nl",
                  "started": "2015-09-17 09:13",
                  "returned": "2015-09-17 09:48",
                  "duration": 35,
                  "licensePlate": "11-22-AA",
                  "licensePlateDealer": "12-ABC-3",
                  "customerDriversLicenseUploaded": false
                }
    /{testDriveId}:
      uriParameters:
       testDriveId:
         displayName: Test Drive ID
         description: ID of the test drive
         type: integer
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "id": 1,
                    "customerName": "Hans de Vries",
                    "customerPhone": "06-12345678",
                    "customerEmail": "Hans@devries.nl",
                    "started": "2015-09-17 09:13",
                    "returned": "2015-09-17 09:48",
                    "duration": 35,
                    "licensePlate": "11-22-AA",
                    "licensePlateDealer": "12-ABC-3"
                  }
      /return:
        post:
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                      "id": 1,
                      "customerName": "Hans de Vries",
                      "customerPhone": "06-12345678",
                      "customerEmail": "Hans@devries.nl",
                      "started": "2015-09-17 09:13",
                      "returned": "2015-09-17 09:48",
                      "duration": 35,
                      "licensePlate": "11-22-AA",
                      "licensePlateDealer": "12-ABC-3"
                    }
      /car:
        get:
          description: |
            Alle parameters zijn optioneel. Als één van de parameters maxWidth of maxHeight niet wordt meegegeven of nul is, dan wordt hij geacht gelijk te zijn aan de andere. Als beide niet worden meegegeven of beide nul zijn, dan wordt het originele bestand teruggegeven.
            Als encoding gelijk is aan de string "base64", dan wordt het plaatje als base64 teruggestuurd. De Content-Type header van de response is dan (bijvoorbeeld) "image/png;base64", en het plaatje kan ingeladen worden in een image tag door src="data:" + contentType + "," + base64data in te stellen.
          queryParameters:
            maxWidth:
              example: 100
            maxHeight:
              example: 120
            encoding:
              example: base64
          responses:
            200:
              description: De foto van de auto dat bij deze testrit geupload is.
              body:
                image/*:
  /loans:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "id": 1,
                    "customerName": "Hans de Vries",
                    "licensePlate": "11-22-AA",
                    "status": "Akkoord",
                    "amountInCents": 450000,
                    "finalized": false
                  }
                ]
    /calculate:
      get:
        queryParameters:
          amount:
            type: integer
            example: 150000
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "amountInCents": "150000",
                      "duration": "12",
                      "totalLoanCost": 155491,
                      "monthlyPayment": 12958,
                      "annualPercentRate": 6900,
                      "yearlyCostPercentage": 6900
                    }
                  ]
    /calculatorConfig:
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "minAmountInCents": 100000,
                    "maxAmountInCents": 2000000,
                    "granularityInCents": 100,
                    "initialQuote": [
                      {
                        "amountInCents": "150000",
                        "duration": "12",
                        "totalLoanCost": 155491,
                        "monthlyPayment": 12958,
                        "annualPercentRate": 6900,
                        "yearlyCostPercentage": 6900
                      }
                    ]
                  }
    /{loanId}:
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "id": 1,
                    "customerName": "Hans de Vries",
                    "licensePlate": "11-22-AA",
                    "status": "Akkoord",
                    "amountInCents": 450000,
                    "finalized": false
                  }
      /finalizeWithOwnershipDocument:
        post:
          description: |
            timeSlotDate en timeSlotLabel zijn slechts verplicht als contactMoment == LATER.
          body:
            multipart/form-data:
              formParameters:
                ownershipDocument:
                  type: file
                  description: image upload
          responses:
            204:
  /contact:
    post:
      description: |
        timeSlotDate en timeSlotLabel zijn slechts verplicht als contactMoment == LATER.
      body:
        multipart/form-data:
          formParameters:
            customerName:
              example: Hans de Vries
            customerPhone:
              example: 06-12345678
            customerEmail:
              example: hans@devries.nl
            customerDriversLicense:
              type: file
              description: image upload
            testDriveId:
              example: 124
            contactMoment:
              example: NOW / LATER
            timeSlotDate:
              example: 2015-11-24
            timeSlotLabel:
              example: middag
      responses:
        204:
    /schedule:
      get:
        description: |
          Contact schedule for the next 5 working days
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "canContactNow" : true,
                    "days" : [ {
                      "date" : "2016-01-22",
                      "slots" : [ "middag", "avond" ]
                    }, {
                      "date" : "2016-01-25",
                      "slots" : [ "ochtend", "middag", "avond" ]
                    }, {
                      "date" : "2016-01-26",
                      "slots" : [ "ochtend", "middag", "avond" ]
                    }, {
                      "date" : "2016-01-27",
                      "slots" : [ "ochtend", "middag", "avond" ]
                    }, {
                      "date" : "2016-01-28",
                      "slots" : [ "ochtend", "middag", "avond" ]
                    } ]
                  }
  /info:
    post:
      description: |
        required: customerEmail and customerName
        optional: amount and duration (both should be either null or non-null)
      body:
        application/json:
          example: |
            {
              "customerEmail": "hans@devries.nl",
              "customerName": "Hans de Vries",
              "amount": 150000,
              "terms": 12
            }
      responses:
        204:
/admin:
  /login:
    post:
      description: |
        Login for an admin
      body:
        application/json:
          example: |
            {
              "username": "isaac",
              "password": "p@ssw0rd"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status": "SUCCESS",
                  "sessionId": "xxxxxxxxx"
                }
            application/json+failure-example:
              example: |
                {
                  "status": "FAILED"
                }
  /logout:
    post:
      description: |
        Logout for an admin.
      responses:
        204:
  /dealers:
    get:
      description: |
        Get a list of dealers
        Sessie authenticatie
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "id": 13,
                    "name": "C. Ardealer",
                    "address": "Straat 1\n9999 AA Plaats",
                    "phone": "06-12345679",
                    "email": "c@ardealer.net",
                    "externalReference": "000020",
                    "active": true
                  }
                ]
    post:
      description: |
        Als id niet null is, wordt een bestaand record geupdated, anders wordt een nieuw record aangemaakt.
        Als password niet null is, dan wordt het password geupdated, anders blijft het hetzelfde.

        Maximum lengtes van de strings:
        - name: 100
        - address: 255
        - email: 255
        - phone: 50
        - externalReference: 50
      body:
        application/json:
          example: |
            {
              "id": null,
              "name": "C. Ardealer",
              "address": "Straat 1\n9999 AA Plaats",
              "phone": "06-12345679",
              "email": "c@ardealer.net",
              "password": "testpassword",
              "externalReference": "000020",
              "active": true
            }
      responses:
        200:
          body:
            application/json:
              example: |
                { "id": 13,
                  "name": "C. Ardealer",
                  "address": "Straat 1\n9999 AA Plaats",
                  "phone": "06-12345679",
                  "email": "c@ardealer.net",
                  "externalReference": "000020",
                  "active": true
                }
  /configuration/contactschedule:
    get:
      responses:
        200:
          body:
            text/plain:
              example: |
                {
                  "maxDays": 5,
                  "schedule":
                  { "monday":
                    [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                      { "label": "middag", "from": "12:30", "to": "16:00" },
                      { "label": "avond", "from": "17:00", "to": "20:00" } ],
                    "tuesday":
                    [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                      { "label": "middag", "from": "12:30", "to": "16:00" },
                      { "label": "avond", "from": "17:00", "to": "20:00" } ],
                    "wednesday":
                    [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                      { "label": "middag", "from": "12:30", "to": "16:00" },
                      { "label": "avond", "from": "17:00", "to": "20:00" } ],
                    "thursday":
                    [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                      { "label": "middag", "from": "12:30", "to": "16:00" },
                      { "label": "avond", "from": "17:00", "to": "20:00" } ],
                    "friday":
                    [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                      { "label": "middag", "from": "12:30", "to": "16:00" },
                      { "label": "avond", "from": "17:00", "to": "20:00" } ],
                    "saturday": [ ],
                    "sunday": [ ]
                  },
                  "exceptions":
                  { "2015-12-24":
                    [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                      { "label": "middag", "from": "12:30", "to": "16:00" },
                      { "label": "kerstavond", "from": "17:00", "to": "19:00" } ],
                    "2015-12-25": [ ],
                    "2015-12-31":
                    [ { "label": "ochtend", "from": "09:00", "to": "12:00" } ]
                  }
                }
    put:
      body:
        text/plain:
          example: |
            {
              "maxDays": 5,
              "schedule":
              { "monday":
                [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                  { "label": "middag", "from": "12:30", "to": "16:00" },
                  { "label": "avond", "from": "17:00", "to": "20:00" } ],
                "tuesday":
                [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                  { "label": "middag", "from": "12:30", "to": "16:00" },
                  { "label": "avond", "from": "17:00", "to": "20:00" } ],
                "wednesday":
                [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                  { "label": "middag", "from": "12:30", "to": "16:00" },
                  { "label": "avond", "from": "17:00", "to": "20:00" } ],
                "thursday":
                [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                  { "label": "middag", "from": "12:30", "to": "16:00" },
                  { "label": "avond", "from": "17:00", "to": "20:00" } ],
                "friday":
                [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                  { "label": "middag", "from": "12:30", "to": "16:00" },
                  { "label": "avond", "from": "17:00", "to": "20:00" } ],
                "saturday": [ ],
                "sunday": [ ]
              },
              "exceptions":
              { "2015-12-24":
                [ { "label": "ochtend", "from": "09:00", "to": "12:00" },
                  { "label": "middag", "from": "12:30", "to": "16:00" },
                  { "label": "kerstavond", "from": "17:00", "to": "19:00" } ],
                "2015-12-25": [ ],
                "2015-12-31":
                [ { "label": "ochtend", "from": "09:00", "to": "12:00" } ]
              }
            }
      responses:
        204:
/system:
  /checkStatus:
    get:
      description: |
        Query the current system status
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "middlewareStatus" : "OK",
                  "dialogueStatus" : "OK",
                  "databaseStatus" : "OK"
                }
  /loans:
    post:
      description: |
        Used by Pangaea logic to update the dealerapp with the latest loan statusses.

        Het veld testDriveId mag null zijn als er geen koppeling gemaakt is. Als een niet-bestaand testDriveId wordt meegegeven, of een testDriveId dat niet gekoppeld is aan de gespecificeerde dealer, dan verschijnt er een warning in de log en wordt de lening niet gekoppeld (maar wel getoond aan de dealer).
      body:
        application/json:
          example: |
            {
              "dealerReference": "apply",
              "dealerLoanReference": "12345",
              "testDriveId": 124,
              "name": "Hans de Vries",
              "amount": 150000,
              "status": "Goedgekeurd"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "dealerReference": "apply",
                  "dealerLoanReference": "12345",
                  "testDriveId": 124,
                  "licensePlate": "AA-BB-11",
                  "name": "Hans de Vries",
                  "amount": 150000,
                  "status": "Goedgekeurd",
                  "finalized": false
                }
